//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        [Key]
        public int UserID { get; set; }
        [DisplayName("Name")]
        public string UserName { get; set; }
        [DisplayName("Position")]
        [Required(ErrorMessage = "Please enter a position")]
        public int UserPosID { get; set; }
        [DisplayName("Is User Present?")]
        public bool IsUserPresent { get; set; }
        //Changed datatype from '.date' to '.datetime'
        [Required(ErrorMessage ="Please enter a date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Date { get; set; }
        [DisplayName("Time-In")]
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        [DisplayName("Time-Out")]
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        
        //mapped error: .edmx check if encountered- Update/ Reftresh data model
        //ownerid mystery
        public int OwnerID { get; set; }

        [NotMapped]
        public List<Pos> PositionCollection { get; set; }

    }
}
